---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mgxcsi-controller
  namespace: {{ .Release.Namespace }}
{{ include "mgx.labels" . | indent 2 }}
spec:
  serviceName: mgxcsi-controller
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: mgxcsi-controller
  template:
    metadata:
{{ include "mgx.labels" . | indent 6 }}
        app: mgxcsi-controller
    spec:
      serviceAccount: mgxcsi-controller-sa
      hostNetwork: true
{{- with .Values.controller.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.controller.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: mgxcsi-provisioner
        image: "{{ .Values.image.csiProvisioner.repository }}:{{ .Values.image.csiProvisioner.tag }}"
        imagePullPolicy: {{ .Values.image.csiProvisioner.pullPolicy }}
        args:
        - "--v=5"
        - "--csi-address=unix:///csi/csi-provisioner.sock"
        - "--timeout=30s"
        - "--retry-interval-start=1s"
        - "--retry-interval-max=30s"
        - "--leader-election=true"
        - "--leader-election-namespace={{ .Release.Namespace }}"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: mgxcsi-resizer
        image: "{{ .Values.image.csiResizer.repository }}:{{ .Values.image.csiResizer.tag }}"
        imagePullPolicy: {{ .Values.image.csiResizer.pullPolicy }}
        args:
        - "--v=5"
        - "--csi-address=unix:///csi/csi-provisioner.sock"
        - "--timeout=30s"
        - "--retry-interval-start=1s"
        - "--retry-interval-max=30s"
        - "--leader-election=true"
        - "--leader-election-namespace={{ .Release.Namespace }}"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: mgxcsi-controller
        image: "{{ .Values.image.mgxcsi.repository }}:{{ .Values.image.mgxcsi.tag }}"
        imagePullPolicy: {{ .Values.image.mgxcsi.pullPolicy }}
        args:
        - "--v=5"
        - "--endpoint=unix:///csi/csi-provisioner.sock"
        - "--nodeid=$(NODE_ID)"
        - "--controller"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: mgxcsi-secret
          mountPath: /etc/csi-secret/secret.json
          subPath: secret.json
          readOnly: true
      - name: mgxcsi-snapshotter
        image: "{{ .Values.image.csiSnapshotter.repository }}:{{ .Values.image.csiSnapshotter.tag }}"
        args:
          - "--csi-address=unix:///csi/csi-provisioner.sock"
          - "--v=5"
          - "--timeout=150s"
          - "--leader-election=true"
          - "--leader-election-namespace={{ .Release.Namespace }}"
        imagePullPolicy: {{ .Values.image.csiSnapshotter.pullPolicy }}
        securityContext:
          privileged: true
        volumeMounts:
          - name: socket-dir
            mountPath: /csi
      volumes:
      - name: socket-dir
        emptyDir:
          medium: "Memory"
      - name: mgxcsi-secret
        secret:
          secretName: mgxcsi-secret
