{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mgxcsi-node-sa
{{- end -}}
{{- if .Values.rbac.create -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mgxcsi-node-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mgxcsi-node-binding
subjects:
- kind: ServiceAccount
  name: mgxcsi-node-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: mgxcsi-node-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
