{{- if .Values.externallyManagedSecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mgxcsi-secret
stringData:
  secret.json: |-
{{ toJson .Values.csiSecret.clusterConfig | indent 4 -}}
{{- end }}
