apiVersion: v1
appVersion: latest
description: CSI Mgx Driver for Kubernetes
name: mgx-csi-driver
version: 0.1
keywords:
- csi
- mgx-csi-driver
home: https://github.com/migrx-io/mgx-csi-driver
sources:
- https://github.com/spdk/spdk-csi/tree/master/charts/spdk-csi
