apiVersion: v1
appVersion: latest
description: CSI Mgx Driver for Kubernetes
name: mgx-csi-driver
version: 0.1.0
keywords:
- csi
- mgx-csi-driver
home: https://github.com/migrx-io/mgx-csi-driver
sources:
- https://github.com/migrx-io/mgx-csi-driver/tree/master/charts/mgx-csi-driver
