driverName: csi.migrx.io

image:
  mgxcsi:
    repository: migrx/mgx-csi-driver
    tag: latest
    pullPolicy: Always
  csiProvisioner:
    repository: registry.k8s.io/sig-storage/csi-provisioner
    tag: v6.0.0
    pullPolicy: IfNotPresent
  csiResizer:
    repository: registry.k8s.io/sig-storage/csi-resizer
    tag: v2.0.0
    pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
    tag: v2.15.0
    pullPolicy: IfNotPresent
  csiSnapshotter:
    repository: registry.k8s.io/sig-storage/csi-snapshotter
    tag: v8.4.0
    pullPolicy: IfNotPresent
  externalSnapshotter:
    repository: registry.k8s.io/sig-storage/snapshot-controller
    tag: v8.4.0
    pullPolicy: IfNotPresent

serviceAccount:
  # Specifies whether a serviceAccount should be created
  create: true

rbac:
  # Specifies whether RBAC resources should be created
  create: true

storageclass:
  # Specifies whether  should be created
  create: true

  # Custom labels (optional)
  # labels: "storage=mgx"

  # Cache size parameters (in MB)
  # minCacheRCacheSize: "1024"
  # minCacheRWCacheSize: "1024"
  # maxCacheRCacheSize: "131072"
  # maxCacheRWCacheSize: "10240"

  # Cache ratio parameters
  # ratioCacheRCacheSize: "0.05"
  # ratioCacheRWCacheSize: "0.1"

  # qosRMBPerSec: "0"
  # qosWMBPerSec: "0"
  # qosRWIOPS: "0"

  # storageEncryptSecret: ""  # name of secret if encryption is enabled
  # storageCompress: ""       # "0" to "9"

externallyManagedSecret:
  # Specifies whether a externallyManagedConfigmap should be created
  create: true 

controller:
  replicas: 1

# The single snapshot controller deployment works for all CSI drivers
# in a cluster. So enable it only if you kubernetes cluster does not
# have a snapshot controller
externalSnapshotter:
  enabled: false
  name: snapshot-controller
  priorityClassName: system-cluster-critical
  controller:
    replicas: 1
  resources:
    limits:
      memory: 300Mi
    requests:
      cpu: 10m
      memory: 20Mi
  # Create volume snapshot CRDs.
  customResourceDefinitions:
    # if set true, VolumeSnapshot, VolumeSnapshotContent and
    # VolumeSnapshotClass CRDs will be created.
    enabled: true

# Configuration for the csiSecret
csiSecret:
  clusterConfig:
    protocol: http
    nodes:
      - localhost:8082
    cluster: main
    ns: main
    username: ""
    password: ""
